[build]
  command = "npm run build" 
  functions = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/weather"
  to = "/server/functions/server.js"
  status = 200

