[build]
  command = "npx vite build" 
  functions = "functions"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/daily-weather"
  to = "/.netlify/functions/server"
  status = 200
