[build]
  command = "cd functions && node server.js" 
  functions = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/weather/*"
  status = 200
  to = "/server/functions/:splat"
